language: node_js
node_js:
  - "6"

env:
  - TRAVIS_CI=1

cache:
  yarn: true
  directories:
    - node_modules

install:
  npm i

script:
  - npm run lint
  - npm run build
  - npm test

notifications:
  # slack: evanliu2968:3Nouwh5OgNugxccCsiFYpUIB
  email:
    recipients:
      - 296823596@qq.com
    on_success: change
    on_failure: always
